ALTER TABLE users
ALTER COLUMN created_at TYPE TIMESTAMP(6) WITHOUT TIME ZONE;

ALTER TABLE users
ALTER COLUMN updated_at TYPE TIMESTAMP(6) WITHOUT TIME ZONE;

ALTER TABLE users
ALTER COLUMN lock_time TYPE TIMESTAMP(6) WITHOUT TIME ZONE;